### PR TITLE
Adds support for Parity addReservedPeer for Management of PoA Parity Clusters

### PR DESCRIPTION
**Pull request by drelu**
### What was wrong?

Related to Issue #1203

### How was it fixed?

Added function addReservedPeer to parity module

### CODE REVIEW

**Comment by kclowes** [comment]
Sorry, my comment was unclear. I meant, will you please add a test (or however many tests you feel are warranted :) ) to the codebase? I think [here](https://github.com/ethereum/web3.py/blob/e4cba0ebcc4b86eef89409d62697b9d6cc6be9b3/web3/_utils/module_testing/parity_module.py) is where it should live. Thanks!

**Comment by drelu** [comment]
> Sorry, my comment was unclear. I meant, will you please add a test (or however many tests you feel are warranted :) ) to the codebase? I think [here](https://github.com/ethereum/web3.py/blob/e4cba0ebcc4b86eef89409d62697b9d6cc6be9b3/web3/_utils/module_testing/parity_module.py) is where it should live. Thanks!

I added the test. However, the RPC Parity backend does not have the addReservedPeer method. Is this a local parity node or mockup the tests are running against? If yes, can you point me to the file, please?

**Comment by pipermerriam** [comment]
Probably need to update the version of parity we are testing against:

- https://github.com/ethereum/web3.py/blob/c4de4746c89b224bfb212e9ed7971ca70024777f/tests/integration/parity/install_parity.py
- https://github.com/ethereum/web3.py/blob/c4de4746c89b224bfb212e9ed7971ca70024777f/.circleci/config.yml#L196

I won't be surprised if the parity fixtures also end up needing to be updated if parity has upgraded it's database schema (which I think it did recently)

**Comment by drelu** [comment]
@pipermerriam Thanks! I do not know the Web3.py CI system. Can you help me upgrading it to Parity 2.3.x stable? I think it make sense to do so as more and more users started to use Parity. A better support from web3.py would be a good thing to have.

**Comment by kclowes** [comment]
I can! Thanks @drelu! I'll wrap this one up

**Comment by kclowes** [comment]
This functionality was merged in #1311. Thanks @drelu!

**Pull request closed without merging**
