### PR TITLE
mark deprecated sha3 method as static

### PR DESCRIPTION
**Pull request by nbt-rezaem**
### What was wrong?

Related to Issue #1349

### How was it fixed?
added @staticmethod annotation to the method

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by nbt-rezaem** [comment]
As all the sha3 tests were removed in v5, I wasn't sure I should add a test for this.

**Comment by pipermerriam** [comment]
Can we get a test added for this (something that fails if the decorator is missing)

**Comment by nbt-rezaem** [comment]
I'll fix the lint error when the tests pass.

**Comment by nbt-rezaem** [comment]
Is the added test good enough?

**Comment by nbt-rezaem** [comment]
Thanks for improving the test. Please merge at your convenience.

**Pull request merged**
