### PR TITLE
Added instructions how to make JSON-RPC faster

### PR DESCRIPTION
**Pull request by miohtama**
### What was wrong?

JSON-RPC is too slow.

### How was it fixed?

Added documentation how to make it faster.

#### Cute Animal Picture

```
                      ,     ,
                  ___('-&&&-')__
                 '.__./     \__.'
     _     _     _ .-'  6  6 \
   /` `--'( ('--` `\         |
  /        ) )      \ \ _   _|
 |        ( (        | (0_._0)
 |         ) )       |/ '---'
 |        ( (        |\_
 |         ) )       |( \,
  \       ((`       / )__/
   |     /:))\     |   d
   |    /:((::\    |
   |   |:::):::|   |
   /   \::&&:::/   \
   \   /;U&::U;\   /
    | | | u:u | | |
    | | \     / | |
jgs | | _|   | _| |
    / \""`   `""/ \
   | __|       | __|
   `"""`       `"""`
```

### CODE REVIEW

**Review by pipermerriam — COMMENTED** [review]
I'm *mildly* uncomfortable with this.  

I'd rather look at how we can support "bring your own JSON decoder..." or just move the library over to use `ujson`, which I'd want to see benchmarks before making this move.

**Comment by miohtama** [comment]
> I'd rather look at how we can support "bring your own JSON decoder..." or just move the library over to use ujson, which I'd want to see benchmarks before making this move.

I agree. However, doing proper modifications to the framework and benchmarking would be more than 10x the amount of work and writing a simple example snippet. Aiming for the low hanging fruit here.

**Comment by miohtama** [comment]
Generic uJSON benchmarks are available on their PyPi page https://pypi.org/project/ujson/

**Review by marcgarreau — APPROVED** [review]
I think we're all on the same page about an ideal path including a native upgrade or some additional configurability, so I tweaked the verbiage to reflect that and warn monkey-patchers that the API could change our from under them. Thanks for the write-up @miohtama.

**Pull request merged**
