### PR TITLE
[WIP] Document Method

### PR DESCRIPTION
**Pull request by kclowes**
### What was wrong?

Method needed some documentation to be used by outside parties. 

Related to Issue #1755 

### How was it fixed?
Added some documentation!

### Todo:
- [ ] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by pipermerriam — COMMENTED** [review]
I think you should do some experiments on how these APIs could be simplified/streamlined before documenting the current API.  My guess is that we can find a cleaner more intuitive way to do this.

**Comment by pipermerriam** [comment]
Experiments that come to mind:

1. Is there a class-based way to do this.  A base class that requires you override certain methods...
2. Is there a decorator based way that really *simple* methods could be written.
3. Are there utilities that we can write that could simplify method creation.  Can we make a "Recipe" or "template" that could be copy/pasta to simplify method creation.

**Comment by kclowes** [comment]
Yeah, good idea. I was thinking about that as I was documenting it. I'll play around with some of those options! It seems like the base class would be the most straightforward so I'll probably start there first, but a decorator might be nice too 🤔

**Comment by pipermerriam** [comment]
Worth noting that these options don't necessarily require reworking the existing API.  Maybe it makes sense to build them as a layer on top of it?  Or to build it as a layer on top of it and then re-factor the middle part once you know the new layer works...  Otherwise you'll be up against refactoring all the work you just did while also trying to refactor the API itself....

**Comment by fselmo** [comment]
@marcgarreau I think we could use some related material from the web3 customization blog post and revamp the documentation around `Method` and attaching methods here to modernize this issue a bit more. I realized we didn't really update the docs after adding that feature in. Thoughts?

**Comment by kclowes** [comment]
Closing - no longer relevant. There is a nice blog post here: https://snakecharmers.ethereum.org/web3-py-patterns-customizations/

**Pull request closed without merging**
