### PR TITLE
Add Snake Case Methods(Shh)

### PR DESCRIPTION
**Pull request by Patil2099**
#1429

### CODE REVIEW

**Comment by Patil2099** [comment]
Is this Correct @pipermerriam?
Thanks!

**Comment by Patil2099** [comment]
@kclowes  @pipermerriam  I made more changes Please Review Them.
Thanks !

**Comment by Patil2099** [comment]
@kclowes I made half changes to the test are those correct? I wanted to know if it is correct then I will proceed with it also can you give me an example if I am wrong

**Comment by Patil2099** [comment]
Okay I get it. I will make a PR in some time

On Aug 29, 2019 10:22 PM, kclowes <notifications@github.com> wrote:

@kclowes commented on this pull request.

________________________________

In tests/core/shh-module/test_shh_key_pair.py<https://github.com/ethereum/web3.py/pull/1433#discussion_r319171815>:

>      assert web3.shh.has_key_pair(key_id)
     assert len(web3.shh.get_public_key(key_id)) == 132
-
-    private_key = web3.shh.get_private_key(key_id)
+    with pytest.warns(DeprecationWarning):
+        private_key = web3.shh.get_private_key(key_id)


This new snake case method shouldn't raise the DeprecationWarning, the old camel case methods should. It would be good to keep the old tests for the camel case methods to make sure they're still working until they're removed, we just want to make sure that every time we use the old methods, we issue a DeprecationWarning. You should be able to copy/paste this test and make another one like:

def test_shh_asymmetric_key_pair(web3, skip_if_testrpc):
    ...
    with pytest.warns(DeprecationWarning):
        key_id = web3.shh.newKeyPair()
        assert web3.shh.hasKeyPair(key_id)
        assert len(web3.shh.getPublicKey(key_id)) == 132
    ...

**Comment by Patil2099** [comment]
@kclowes  I made some more changes. Please review them and let me know if some other change is required.

**Comment by Patil2099** [comment]
@kclowes @pipermerriam I made all the changes that were required. Please Review My PR

**Comment by kclowes** [comment]
@Patil2099 All the tests should be passing. Once those are all green, I'll take a closer look!

**Comment by Patil2099** [comment]
@kclowes Can you please help a little bit?
Thanks!

**Comment by kclowes** [comment]
@Patil2099 I made some updates, and screwed up your history in the process. Sorry about that. I'll pick it back up on Monday.

**Comment by kclowes** [comment]
@Patil2099 I got the tests running, and made some updates to the tests to get them passing. I also squashed all the commits down to one. I'm happy to expand on either of those things more if you are interested in picking up another module. Thanks for all of your work!

**Pull request merged**
