### PR TITLE
Add script to test packaging

### PR DESCRIPTION
**Pull request by kclowes**
### What was wrong?
We had a release (5.3.1) that was missing a dependency. Unfortunately, that wasn't caught until after the release. 

Related to Issue #1540 

### How was it fixed?
I stole a script from trinity that installs the release to a temporary virtualenv for testing.

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)
- [x] Add this to CI (ex. https://github.com/ethereum/trinity/pull/106/files#diff-b91f3d5bd63fcd17221b267e851608e8R61-R64)

#### Cute Animal Picture

image

### CODE REVIEW

**Comment by kclowes** [comment]
@pipermerriam It looks like this script only builds from the wheel that is already in `dist/`. Does the Trinity team usually do a new local build and then run this script, or what is your preferred flow?

**Comment by pipermerriam** [comment]
cc @carver did you setup the wheel tests for trinity?

**Comment by veox** [comment]
@kclowes The `dist` is built as part of the `tox` job; here's the particular lines:

https://github.com/ethereum/trinity/pull/106/files#diff-b91f3d5bd63fcd17221b267e851608e8R61-R64

https://github.com/ethereum/trinity/pull/106/files# is the rest of that PR, of course.

**Comment by kclowes** [comment]
Aha! Thanks for looking into that @veox!

**Comment by kclowes** [comment]
Nope, good catch. Instead of adding to CI, I added to the Makefile and the README similar to what Trinity has going on. There is a smoke test in CI that makes sure that the wheel builds and that we can import web3 though.

**Pull request merged**
