### PR TITLE
refactored the code by using 'yield from' instead of 'yield'

### PR DESCRIPTION
**Pull request by Harmouch101**
Signed-off-by: Harmouch101 <mahmoudddharmouchhh@gmail.com>

### What was wrong?

code refactoring! 
###  Todo:
 - [ ]  Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)
#### Cute Animal Picture

cute kitten

### CODE REVIEW

**Comment by Harmouch101** [comment]
@kclowes Yoooo! Why isn't this brach merged yet? Is there something wrong? I just wanted to know cause it is my first time contributing to this repo.

**Comment by pipermerriam** [comment]
@Harmouch101 thank you for your enthusiasm. I don't think we'll be accepting this change.  It reduces readability with very little gain.

**Comment by pipermerriam** [comment]
Also, in the future, you might try to reframe your questions.

> Yoooo! Why isn't this branch merged yet? Is there something wrong? I just wanted to know cause it is my first time contributing to this repo.

This implies that "we" the maintainers have failed to do something that we should have done.  You might try it like this next time.

> Yoooo, I'm wondering if there are any issues with this pull request that you'd like me to clean up.

**Comment by Harmouch101** [comment]
Alright. Cool! Thanks for your suggestion. I'll try my best to be nice next time. My bad!

**Pull request closed without merging**
