### PR TITLE
Add black to ethpm

### PR DESCRIPTION
**Pull request by kclowes**
### What was wrong?

Black is finally stable, so pulling it in. One module at a time. 

Related to Issue #1416 

### How was it fixed?
added the Black dependency, let it make any fixes.

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by Harmouch101** [comment]
How about using [pre-commit](https://pre-commit.com/) to automate formatting stuff?

**Comment by kclowes** [comment]
> How about using [pre-commit](https://pre-commit.com/) to automate formatting stuff?

@Harmouch101 That looks like a good option, but I'm going to hold off for now. If we decide running black is too clunky then I may pull it in. Thanks for the suggestion!

**Review by pacrob — APPROVED** [review]
lgtm!

**Comment by fselmo** [comment]
I was originally thinking we could set the line-length to `100` since that's been our standard for some time but I don't feel strongly about that. It still produces a lot of diff (even more I think). Maybe we should just let black do its thing?

This change would do that within `pyproject.toml`:

```toml
[tool.black]
line-length = 100

**Review by fselmo — APPROVED** [review]
lgtm! Excited for this addition. I just left one comment to think about before we start changing everything to black across the code base. But maybe we should just leave it all default black settings since that's kind of the point 😅 .

**Comment by pacrob** [comment]
>... Maybe we should just let black do its thing?
+1 for default line length 88

**Comment by kclowes** [comment]
Okay, I'll leave line length at 88. Thanks!

**Comment by kclowes** [comment]
Okay, I'll leave line length at 88. Thanks!

**Pull request merged**
