### PR TITLE
Upgrade eth-account to >=0.5.1

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

eth-account was old

(Also, testing the recent eth-account release)

### How was it fixed?

upgraded it

### Todo:
- [ ] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by kclowes** [comment]
Thanks @carver! When I was testing locally with 0.5.0 I noticed that the new hdaccount features weren't working because there were some txt files missing from the eth-account release. Did you happen to make sure this works locally for you?

**Comment by kclowes** [comment]
I have [this PR](https://github.com/ethereum/eth-account/pull/99) up which adds package_data to the setup.py in eth-account, which seemed to fix the problem for me, but I'm curious if you're seeing the same thing or if it's just me having an environment issue.

**Comment by carver** [comment]
> Thanks @carver! When I was testing locally with 0.5.0 I noticed that the new hdaccount features weren't working because there were some txt files missing from the eth-account release. Did you happen to make sure this works locally for you?

Nope! Glad you were able to take a closer look than I was.

**Comment by kclowes** [comment]
Closing in favor of #1622!

**Pull request closed without merging**
