### PR TITLE
adding missing apt packages

### PR DESCRIPTION
**Pull request by ycdk**
**Problem**: Some packages missing for compiling in clean virtualenv

**Solution**: Add packages to `apt` command

### CODE REVIEW

**Comment by carver** [comment]
Cool, thanks for fleshing this out a bit.

Why do you want to install `libffi-dev`? I don't have it locally.

**Comment by carver** [comment]
I'm not certain all of these are required, but it's relatively low cost to overinstall a few standard dev libraries, so I'm merging.

**Comment by ycdk** [comment]
sorry @carver, did not see note while travelling.   if i remember, the `apt` packages were required to build `pyethereum` and its `cffi` dependency. 

maybe we really copy the full list from that webpage:
https://github.com/ethereum/pyethereum/#installation

**Comment by carver** [comment]
Since we're in the process of removing the pyethereum dependency, I probably won't go add the full list, but if you wanted to, I'd merge it. (maybe separating the dependencies into a separate line, so they are easy to remove again when pyethereum is fully removed)

**Pull request merged**
