### PR TITLE
Adding PyChain 2022 banner

### PR DESCRIPTION
**Pull request by miohtama**
### What was wrong?

Related to Issue #2665

### How was it fixed?

- Included the banner image
- Override the searchbox.html template from Sphinx RTD theme with minimal changes
- Added link to https://www.pychain.org
- Added a link tag to identify the traffic coming through the docs
- Added necessary CSS changes to format the banner nicely

Screenshots:

image

image

#### Cute Animal Picture

```
            / . .\
MT          \  ---<
             \  /
   __________/ /
-=:___________/
```

### CODE REVIEW

**Comment by miohtama** [comment]
I think those CircleCI errors are unrelated to my pull request.

**Comment by fselmo** [comment]
> I think those CircleCI errors are unrelated to my pull request.

Yeah, they are unrelated. We'll get that fixed and circle back here. Thanks Mikko 👍🏼

**Review by fselmo — APPROVED** [review]
lgtm 👍🏼

**Comment by miohtama** [comment]
I just noticed the change is only live in "master", not "stable" branch that everyone is using.

Is there a way to get this included in stable somehow?

image

image

**Pull request merged**
