### PR TITLE
[WIP] Fix CircleCI Parity failures (missing shared libs)

### PR DESCRIPTION
**Pull request by veox**
### What was wrong?

CI fails due to `parity` not finding its desired shared libs.

Previous attempt by @voith: PR #865

### How was it fixed?

It wasn't (still WIP).

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

Source: [/r/aww](https://www.reddit.com/r/aww/comments/6zqztv/disney_eyes/)

### CODE REVIEW

**Comment by voith** [comment]
@veox I tried v1.9.7 earlier, but failed. The only solution that I can think of is building parity from source so that it uses the libssl that is installed on the machine. 
The current problem is that the script downloads a  pre-compiled binary which is not compatible with the machine.

**Comment by veox** [comment]
Yes, the "vanity" builds by Parity are dynamically-linked.

**Comment by voith** [comment]
@veox You'd be better off debugging this using circleci's ssh debug mode. Printing info this way will take longer. However, you'll have to enable Circle for your fork!

**Comment by veox** [comment]
Yeah, this is getting too noisy, I should indeed be doing it on my own fork.

**Comment by veox** [comment]
Closing for now.

**Pull request closed without merging**
