### PR TITLE
removed deprecated methods from eth and geth

### PR DESCRIPTION
**Pull request by dbfreem**
### What was wrong?

Removed deprecated methods from eth and geth

Related to Issue #1416 

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

### CODE REVIEW

**Comment by dbfreem** [comment]
Going to set this back to draft becuase I thought protocolVersion wasn't used anymore but it is. So I need to add it back.

**Comment by dbfreem** [comment]
@kclowes based on [this comment](https://github.com/ethereum/web3.py/blob/master/tests/integration/go_ethereum/common.py#L50) it looks like `eth_versionModule` was removed from geth so was my initial thoughts correct around removing the `protocole_version` and `protocolVersion` methods from eth?

**Comment by kclowes** [comment]
> @kclowes based on [this comment](https://github.com/ethereum/web3.py/blob/master/tests/integration/go_ethereum/common.py#L50) it looks like eth_versionModule was removed from geth so was my initial thoughts correct around removing the protocole_version and protocolVersion methods from eth?

Yeah, protocolVersion can be removed. We'll need to be sure that we have a deprecation warning in v5 though. Let me know if you want me to add an issue to track the v5 deprecation. Thanks!

**Comment by dbfreem** [comment]
I am busy for the next week so it may be good to merge this and create an issue for v5 deprecation and tag me on it.

**Comment by dbfreem** [comment]
`protocol_version` is already [deprecated ](https://github.com/ethereum/web3.py/blob/master/web3/eth.py#L570,L584) so this PR should be good to go.

**Review by kclowes — APPROVED** [review]
I just checked and it looks like we do have a deprecation warning in v5, so this should be good to go. Thanks!

**Pull request merged**
