### PR TITLE
[WIP] Replace ConciseContract with ContractCaller. 

### PR DESCRIPTION
**Pull request by Exef**
### What was wrong?

Related to Issue #1025 

### How was it fixed?

I renamed ConciceContract to ContractReader and ConciseMethod to ReaderMethod. Also removed all unwanted methods allowance from ReaderMethod.

TODO:
- [ ] Write documentation to the ContractCaller
- [ ] Write test for the ContractCaller
- [ ] Write test for deprecation message for ConciseContract and ImplicitContract

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by dylanjw** [comment]
The description of the work in #1025 is lacking.  Rather than replacing, ConciseContract should have deprecation warnings added, and the ContractReader should be added as a new feature.  After the next major version bump, ConciseContract can be deleted (v6).  Going through a deprectation cycle will allow us to not break anyones code that depends on ConciseContract, and give them ample time to update before it is removed.

**Comment by Exef** [comment]
ok, I'll update this PR in that way.

**Comment by carver** [comment]
BTW, if you rebase against master, the doctest failure will go away.

**Comment by kclowes** [comment]
Hi @Exef! I started working on this same issue to get familiar with the library and saw this. Are you interested in completing the todos you have listed above or can I finish it up? :)

**Comment by kclowes** [comment]
This has been implemented in #1227. Thank you for the effort @Exef!

**Pull request closed without merging**
