### PR TITLE
Allow passing os as an env variable for parity to install correct executable

### PR DESCRIPTION
**Pull request by voith**
### What was wrong?
Currently, the os is hardcoded to debian in the parity install script

### How was it fixed?
Allow passing os as an env variable for parity to install correct executable

### CODE REVIEW

**Comment by dylanjw** [comment]
@voith Do you want to add PARITY_OS env vars to the circleci + travis configurations?

**Comment by voith** [comment]
@dylanjw done

**Comment by voith** [comment]
DO NOT merge this PR. I want to see if I can get the travis builds passing by setting `PARITY_OS=linux`.
However, I'm on mobile at the moment. Will give it try once I'm on my laptop.

**Comment by voith** [comment]
setting `PARITY_OS=linux` didn't work. Here's the build: https://travis-ci.org/voith/web3.py/jobs/388148390.

**Comment by pipermerriam** [comment]
@voith is this good to go?

**Comment by voith** [comment]
@pipermerriam Yes. Although this doesn't fix the travis failures, this change helps when testing locally.

**Pull request merged**
