### PR TITLE
Allow block identifier for Contract.estimateGas

### PR DESCRIPTION
**Pull request by palango**
### What was wrong?

Related to Issue https://github.com/ethereum/web3.py/issues/1011 and PR https://github.com/ethereum/web3.py/pull/1046

### How was it fixed?

Adds `block_identifier` to `Contract.estimateGas(...)`

### Todo:
- [ ] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by marcgarreau** [comment]
Thanks for the PR @palango. Can we get one or more tests documenting this change?

**Comment by palango** [comment]
> Thanks for the PR @palango. Can we get one or more tests documenting this change?

Sure, I'll add some tests, but let me know if you want something particular.

**Comment by palango** [comment]
@marcgarreau I wonder how #1046 actually works, the `eth-tester` still doesn't have a `block_identifier` parameter: https://github.com/ethereum/eth-tester/blob/035dde2c4ebc10a205748b37b940cb519251d9da/eth_tester/main.py#L431

Do I need to add that there?

**Comment by marcgarreau** [comment]
Coming up to speed on the block identifier... just curious, if you're testing this locally, are you using parity/openethereum? Looks like the feature [is available](https://openethereum.github.io/wiki/JSONRPC-eth-module) on that client, but not geth. 

If we follow the precedent set by #1046, then we'd skip the implemention in eth-tester, and document that in the tests similar to this [xfail](https://github.com/ethereum/web3.py/pull/1046/files#diff-ffb8c252611a75915c8ad13c0ec1bc4c).

**Comment by palango** [comment]
> Coming up to speed on the block identifier... just curious, if you're testing this locally, are you using parity/openethereum? Looks like the feature [is available](https://openethereum.github.io/wiki/JSONRPC-eth-module) on that client, but not geth.

Yes, openethereum supports it, but geth not. See https://github.com/ethereum/go-ethereum/issues/2586


> If we follow the precedent set by #1046, then we'd skip the implemention in eth-tester, and document that in the tests similar to this [xfail](https://github.com/ethereum/web3.py/pull/1046/files#diff-ffb8c252611a75915c8ad13c0ec1bc4c).

I remember vaguely that I read somewhere that py-evm supports a block identifier on this call. I f so, it would be nice to support it.

**Comment by marcgarreau** [comment]
Had a quick chat with @carver who confirmed py-evm does have support for the block identifier, and that eth-tester would need to be updated to that effect. Are you interested in giving that a shot?

**Comment by palango** [comment]
> Are you interested in giving that a shot?

I don't have time for that at the moment. I'll come back if that gets better.

**Comment by marcgarreau** [comment]
(started work on this today)

**Comment by marcgarreau** [comment]
There's a [PR up in eth-tester](https://github.com/ethereum/eth-tester/pull/189) which satisfies these failing tests (and hopefully doesn't create any new ones).

**Comment by carver** [comment]
We can try to get new eth-tester released on Monday. In the meantime, it is possible to pin a requirement to a github-hosted commit, if you want to try it out. @marcgarreau

**Pull request merged**
