### PR TITLE
Python 3.11 Support

### PR DESCRIPTION
**Pull request by kclowes**
### What was wrong?
Needed to support Python 3.11.

### How was it fixed?
Updated our upstream libraries, pulled them in here. 

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by Uxio0** [comment]
Just adding here this issue I found when compiling pysha3 for Python 3.11: https://github.com/tiran/pysha3/issues/30 . It would be a shame to fallback to `pycryptodome` as `pysha3` is way faster

**Comment by kclowes** [comment]
@Uxio0 that's a bummer that your issue got closed/that `pysha3` is no longer maintained. I don't see `keccak` in the hashlib module either. @carver raised [an issue](https://github.com/ethereum/eth-hash/issues/44) in `eth-hash` to remove pysha3 from the backends.

**Comment by Uxio0** [comment]
@kclowes I tested master branch for `pysha3` and it works on Python 3.11. I can fork it and release a new version

**Comment by Uxio0** [comment]
Here it is: https://pypi.org/project/safe-pysha3/

**Comment by aliking7** [comment]
Please check it out? what should i do now?
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from web3 import Web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\web3\__init__.py", line 6, in <module>
    from eth_account import (
  File "C:\Python311\Lib\site-packages\eth_account\__init__.py", line 1, in <module>
    from eth_account.account import (
  File "C:\Python311\Lib\site-packages\eth_account\account.py", line 59, in <module>
    from eth_account.messages import (
  File "C:\Python311\Lib\site-packages\eth_account\messages.py", line 26, in <module>
    from eth_account._utils.structured_data.hashing import (
  File "C:\Python311\Lib\site-packages\eth_account\_utils\structured_data\hashing.py", line 9, in <module>
    from eth_abi import (
  File "C:\Python311\Lib\site-packages\eth_abi\__init__.py", line 6, in <module>
    from eth_abi.abi import (  # NOQA
  File "C:\Python311\Lib\site-packages\eth_abi\abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "C:\Python311\Lib\site-packages\eth_abi\codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "C:\Python311\Lib\site-packages\eth_abi\decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "C:\Python311\Lib\site-packages\eth_abi\base.py", line 7, in <module>
    from .grammar import (
  File "C:\Python311\Lib\site-packages\eth_abi\grammar.py", line 4, in <module>
    import parsimonious
  File "C:\Python311\Lib\site-packages\parsimonious\__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "C:\Python311\Lib\site-packages\parsimonious\grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "C:\Python311\Lib\site-packages\parsimonious\expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (C:\Python311\Lib\inspect.py)

**Comment by stepollo2** [comment]
@aliking7
as per parsimonious changelog:

0.9.0

        Add support for Python 3.7, 3.8, 3.9, 3.10 (righthandabacus, Lonnen)
        Drop support for Python 2.x, 3.3, 3.4 (righthandabacus, Lonnen)

https://github.com/erikrose/parsimonious

I guess currently web3.py uses 0.8.1

**Comment by charles-cooper** [comment]
@kclowes i think eth-bloom is also pinning to an old version of eth-hash: https://github.com/ethereum/eth-bloom/blob/03378183fa3afefff0f366f1a8e9a31d56363b28/setup.py#L44

**Comment by charles-cooper** [comment]
here's what happens when trying to install web3.py and eth-hash==0.5.1 at the same time:
image

**Comment by kclowes** [comment]
Yeah, we have to update our whole dependency stack. @fselmo was going to start looking into `eth-bloom` today.

**Review by fselmo — APPROVED** [review]
lgtm! Thanks! Just missing a newsfragment and adding 3.11 to the list [here](https://github.com/ethereum/web3.py/blob/master/setup.py#L112-L116).

**Comment by yabirgb** [comment]
Thanks for the work in this PR! Is this going to ship in the 5.x.x versions?

**Comment by kclowes** [comment]
@yabirgb this will not ship in the 5.x versions because there were some breaking dependency changes.

**Comment by bh2smith** [comment]
Not sure if some indirect requirement was changed, but I had to manually add a dependency to my project that was included in previous versions (namely ipfshttpclient)

```
# web3==5.31.3
# For Python 3.11 support. Waiting for official release.
# https://pypi.org/project/web3/#history
web3==6.0.0b9
# Python 3.11 seems to need this explicitly declared now for some reason.
ipfshttpclient==0.8.0a2
```

[Here is a corresponding failing CI](https://github.com/cowprotocol/dune-sync/actions/runs/3910510018/jobs/6682795124) without the manually added additional dependency.

**Comment by kclowes** [comment]
Thank you for the report! Fix is at #2775. It should be released next week in v6b10.

> Would anyone be opposed to me adding this to the README?

Not at all! Thank you!

**Comment by lamoboos223** [comment]
i still have the issue in python3.11

image

**Comment by kclowes** [comment]
@lamoboos223 thanks for the reminder. I just released `v6.0.0-beta.10` that has the fix. If you upgrade and still see the problem, please open a new issue!

**Pull request merged**
