### PR TITLE
deprecated estimateGas and buildTransaction in v5 contract

### PR DESCRIPTION
**Pull request by dbfreem**
### What was wrong?

Deprecating buildTransaction and estimateGas in the v5 branch. I will remove them in the asyncify-contract branch so they are effectively removed in v6

Related to Issue #1416

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

### CODE REVIEW

**Comment by dbfreem** [comment]
just realized doc changes are still needed here I will make those in the next couple days

**Comment by dbfreem** [comment]
Actually, there isn't a doc portion of this. Since there will not be docs published for the v5 branch. At least,  I wouldn't think there would be. I deprecated the methods but did not update the docs. I will rename all the methods in the docs on the asyncify-contract branch.

**Comment by kclowes** [comment]
Thanks @dbfreem! The docs on this branch (v5) should maintain the deprecation warnings. The doc deprecation warnings can be removed in `master` when we remove the `camelCase` methods. 

The changes in `contract` look good. If you check out the core test output on circleci, there are a bunch of deprecation warnings for the camelCase -> snake_case change, so extra credit for cleaning those up too if you're up for it. I haven't looked, but I think there will also probably be doc changes needed in `docs/contract.rst` as well. Thanks again!

**Comment by dbfreem** [comment]
I am not sure how I got the docs out of sync here. My intention was to not remove those etc docs in v5. I was going to update the contract docs in v5. I will take care of this in a couple days.

**Pull request closed without merging**
