### PR TITLE
Upgrade Sphinx

### LINKED ISSUE #1644: Upgrade Sphinx to v3.0+
* Version: 5.9+

### What was wrong?
The Sphinx dependency wasn't pinned and when Sphinx 3.0 came out some of our doctests broke. It's currently pinned to  >=2.4.4,<3. 

### How can it be fixed?
Pin Sphinx between 3.0 and 4, and then fix any failing tests.

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #1644

### CODE REVIEW

**Comment by Patil2099** [comment]
@kclowes  @pipermerriam  Can you please help in solving this one failing test?

**Comment by kclowes** [comment]
Yep, I'll take a look. Thanks!

**Comment by kclowes** [comment]
@Patil2099 I took a look this morning and couldn't figure it out quickly. This isn't top priority for me right now, so I'm not going to keep digging into it. If you want to keep working on it, I'd take a look at the breaking changes from Sphinx's v2 to v3.x and see if you can find anything in there that may be raising a new warning. Or we can close the PR and try again later. Thanks!

**Comment by marcgarreau** [comment]
Thanks for your interest in contributing! This update was addressed in #1977, though.

**Pull request closed without merging**
