### PR TITLE
Add async chain_id setter

### PR DESCRIPTION
**Pull request by kclowes**
### What was wrong?
The new chain_id flow wasn't available on async eth.

Related to Issue #2207 

### How was it fixed?
Added it!

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by pacrob — APPROVED** [review]
lgtm!

**Review by fselmo — APPROVED** [review]
lgtm!

**Comment by fselmo** [comment]
I wonder if we should have a validation that it can only be set to the `eth_chainId` value. But we can have this be a separate discussion I think. This completes the current flow 👌

**Comment by kclowes** [comment]
I am going to merge this, but like we talked about this morning, I'll check on the original issue to see if there is any reason to allow a different `chain_id` to be set.

**Pull request merged**
