### PR TITLE
Gracefully handle when the name key does not exist in the contract abi

### PR DESCRIPTION
**Pull request by RoyLee**
### What was wrong?
Some abi contracts do not have a name key. This will gracefully handle those cases by preventing an errors when that occurs.

Related to Issue [#1655](https://github.com/ethereum/web3.py/issues/1655)

### How was it fixed?
Use `get` method to return a default value of '' when there is no `name` key.

### Todo:
- [ ] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture
🐱

### CODE REVIEW

**Comment by kclowes** [comment]
@RoyLee Thanks for opening this PR! Do you have a real ABI example with a function that has no name? I may be wrong, but it looks to me from the [Solidity ABI spec](https://solidity.readthedocs.io/en/v0.7.0/abi-spec.html#json) that the only functions that don't have a name are fallback and constructor functions, which means that if this `NameError` is raised, the ABI is malformed. If that's case, I think the better change would be to raise a different error with a better message, rather than ignoring it with a `get`. And probably the best solution is to have an ABI validator as discussed [here](https://github.com/ethereum/web3.py/issues/1655#issuecomment-630908773).

@pipermerriam I'm curious to hear your thoughts here too!

**Comment by RoyLee** [comment]
@kclowes In my specific case the name I was trying to call did exist in the application binary interface but there just happened to be an element in the ABI that did not have a name key in it. Viewing the solidity documentation I do not see any of the fields including name are required and do not believe an exception should be raised because the `filter_by_name`'s role is not to validate/enforce the ABI.

**Comment by marcgarreau** [comment]
@RoyLee - if you've used a tool that generated an ABI function without a name, please let us know which one/how to reproduce it.

While still unclear to me when we'd run into one of these nameless functions outside of fallback/constructor, I do agree that this `filter_by_name` function is probably the wrong place to enforce the validation. As Piper points out in the linked issue, a separate feature for validation/normalization might be the 'real' answer here, but I'm okay with this change set alone.

**Comment by RoyLee** [comment]
@marcgarreau An example of an ABI that I assume is highly used via the web3 library is the Uniswap v2 router smart contract: https://etherscan.io/address/0x7a250d5630b4cf539739df2c5dacb4c659f2488d#code
There are multiple elements without a name.

**Comment by kclowes** [comment]
@RoyLee I grabbed the ABI at that address and ran a quick script on it, but the only functions that didn't have names are the `fallback` and `constructor` functions. We have separate logic for these functions that account for the functions not having a name. I am hesitant to merge this without an example of an ABI where functions don't have names. Let us know if you're using a different tool or something to get the ABI, and I'd be happy to take another look.

**Comment by fselmo** [comment]
Closing due to inactivity and missing clarifying information. Feel free to re-open if there is more information here and if this is still relevant.

**Pull request closed without merging**
