### PR TITLE
Upgrade websockets to >=9.1.0

### PR DESCRIPTION
**Pull request by kclowes**
### What was wrong?
Websockets needed to be upgraded!

### How was it fixed?
Upgraded websockets to >=9.1.0, <10

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by dixonwhitmire** [comment]
Hello! This dependency update will help us resolve a build issue we have with one of our applications. Please let me know if our team can help with this effort!

Thanks!

**Comment by kclowes** [comment]
@dixonwhitmire thanks for the offer! Once I get CI working this should be good to go!

**Comment by dixonwhitmire** [comment]
> @dixonwhitmire thanks for the offer! Once I get CI working this should be good to go!

Thank you very much!

**Review by fselmo — APPROVED** [review]
I think this workaround for the docs_steps to install web3 within a separate step should be good for now! maybe we can revisit this at some point

**Comment by dixonwhitmire** [comment]
@kclowes - thank you for updating the websocket dependency!

**Pull request merged**
