### PR TITLE
update examples and web3.eth with checksummed addresses

### PR DESCRIPTION
**Pull request by crawfordleeds**
### What was wrong?

Various aspects of the docs showed examples without checksummed addresses where doing so currently would throw an error. 

Related to Issue #1388

### How was it fixed?

I have started updating addresses in the docs to be checksummed. I haven't done a thorough review. Will do so over the next few days. If you think I'm missing something please let me know.

#### Cute Animal Picture

IMG_3407

### CODE REVIEW

**Comment by kclowes** [comment]
:tada: This is awesome, thank you! I did a quick search and saw that there are a bunch more in `docs/web3.geth.rst`, `docs/web3.parity.rst`, and `docs/web3.eth.rst` and a few in `docs/overview.rst` in the `keccak` and `solidityKeccak` documentation. I also see one in `docs/contracts.rst` line 808 (but there may be more). Thanks again!

**Comment by crawfordleeds** [comment]
Thanks for the catches, @kclowes. I was doing this while at the vet with my dog on my lap - I shouldn't be allowed to push anything without first viewing on a bigger screen. Will get on it asap. Thanks!

**Comment by crawfordleeds** [comment]
Hey @kclowes any idea of the the cause of those test failures? It happened with one of my earlier commits too. Later commits passed but I don't think I ever changed anything of significance that would lead to the pass/fail difference.

**Comment by crawfordleeds** [comment]
@kclowes thanks for the catches. It would be criminal for me to pass the last 3 fixes on to you. Should be updated in the PR now, thanks!

**Comment by kclowes** [comment]
Lol, thank you so much! This is awesome. I'll rebase and merge first thing tomorrow. Thanks again!

**Pull request merged**
