### PR TITLE
JSON RPC request id from 1.

### PR DESCRIPTION
**Pull request by dingguijin**
Since https://cloudflare-eth.com can not parse id from 0.

### What was wrong?

Related to Issue #2145.

Change request_counter start from 1.

### CODE REVIEW

**Comment by dingguijin** [comment]
JSON RPC request id from 1.

**Comment by fselmo** [comment]
@dingguijin Thanks for submitting this. We did some discussing and think it would be ideal to instead add an optional kwarg when initializing the provider that would set the start `id` for the JSON-RPC call. This would help not introduce a possible breaking change if anyone is tracking these id's in their code and allows for customization of this value on instantiation.

It would be good to include tests for this as well... let me know if you want to work on this otherwise I can submit a quick PR no problem.

Thanks again for your contribution!

**Comment by dingguijin** [comment]
@fselmo Obviously It is a better idea to add an optional kwarg to set id for JSON-RPC call. I am glad to do that changing code and adding unittest. But I do not know the PR process of this project. It would be good if you could help me do that.

Thanks for your reply.

**Comment by fselmo** [comment]
> @fselmo Obviously It is a better idea to add an optional kwarg to set id for JSON-RPC call. I am glad to do that changing code and adding unittest. But I do not know the PR process of this project. It would be good if you could help me do that.
> 
> Thanks for your reply.

Absolutely. Glad to point you in the right direction.

[Here](https://web3py.readthedocs.io/en/latest/contributing.html#pull-requests) is a good reference for the PR process. We would be adding a `2151.feature.rst` file with a brief description of the task. Let me know if you have any specific questions along the way and I'd be happy to help!

**Comment by dingguijin** [comment]
> @dingguijin Thanks for submitting this. We did some discussing and think it would be ideal to instead add an optional kwarg when initializing the provider that would set the start `id` for the JSON-RPC call. This would help not introduce a possible breaking change if anyone is tracking these id's in their code and allows for customization of this value on instantiation.
> 
> It would be good to include tests for this as well... let me know if you want to work on this otherwise I can submit a quick PR no problem.
> 
> Thanks again for your contribution!

**Comment by dingguijin** [comment]
> > @fselmo Obviously It is a better idea to add an optional kwarg to set id for JSON-RPC call. I am glad to do that changing code and adding unittest. But I do not know the PR process of this project. It would be good if you could help me do that.
> > Thanks for your reply.
> 
> Absolutely. Glad to point you in the right direction.
> 
> [Here](https://web3py.readthedocs.io/en/latest/contributing.html#pull-requests) is a good reference for the PR process. We would be adding a `2151.feature.rst` file to the newsfragments with a brief description of the task. We should also update the docs with the new feature in the appropriate section.
> 
> Let me know if you have any specific questions along the way and I'd be happy to help!

@fselmo Thanks,

After some investigations about id of JSON-RPC spec (https://www.jsonrpc.org/specification), when id is equal to 0, it would be inexplicit to NULL, JSON-RPC server could handle this request as a notification and imagine JSON-RPC client will not care the response.

So, JSON-RPC request id from 1 or adding a request_id as construtor parameter of HTTPProvider?

**Pull request closed without merging**
