### PR TITLE
Remove Parity integration tests and references & update Parity API docs

### PR DESCRIPTION
**Pull request by mgmanzella**
### What was wrong?

Closes https://github.com/ethereum/web3.py/issues/2102

### How was it fixed?
- Deleted integration tests within the `tests/integration/` directory
- Removed references in `web3/_utils/module_testing/__init__.py`
- Removed references in tox.ini (command `tox -e py38-integration-parity` no longer exists)
- Deleted `tests/integration/parity-2.5.13-fixture.zip`
- Removed `ParityPersonalModuleTest` class in `web3/_utils/module_testing/personal_module.py`
- Remove references to the parity integration fixture in `docs/contributing.rst`
- Remove `PARITY_` environment variables in `tox.ini`

### Todo:
- [x] Update documentation to reflect Parity being deprecated 
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->
(me trying to get into open source in crypto)

### CODE REVIEW

**Comment by kclowes** [comment]
Thanks for the PR @mgmanzella!

> What branch should I be targeting for merge in this PR? Are there docs on release strategy?

The branch to target is master. We (the maintainers) release once we have a few changes ready to go, so no need to worry about that. 

> Should documentation be updated to reflect Parity no longer works or should that be a separate issue?

Yes please! If you have time, it would be nice to add a note to the top of the Parity API document, otherwise I will get to it in a bit. There is an example of the `note` syntax in `docs/web3.eth.rst` on line 480. And you can preview what your changes will look like by doing a `make docs` from the command line. Thanks again!

**Comment by mgmanzella** [comment]
> Yes please! If you have time, it would be nice to add a note to the top of the Parity API document, otherwise I will get to it in a bit. There is an example of the note syntax in docs/web3.eth.rst on line 480. And you can preview what your changes will look like by doing a make docs from the command line. Thanks again!

@kclowes sounds good!! will add these changes 👍 also are the test failures expected? they only seem related to goeth and i can replicate locally

**Comment by kclowes** [comment]
They're intermittent failures, unfortunately. I just re-ran them though, and it looks like they all passed, so I think we're all good to go there!

**Comment by kclowes** [comment]
@mgmanzella I forgot to clarify in my last comment that it's possible that the Parity API still works, we're just no longer supporting it. So I would add a note to the docs that says something along the lines of:
Parity is no longer maintained, so this API is no longer receiving active updates. It will be removed in v6.

**Comment by mgmanzella** [comment]
@kclowes should be ready to review 🙏

**Comment by mgmanzella** [comment]
> The changes here look good, @mgmanzella! Thank you! There are a few more things that need to be removed if you're up for it:
> 
> * there are still some `ParityPersonalModuleTests` floating around in `web3/_utils/module_testing/personal_module.py` - we should probably remove are references to the parity integration fixture in `docs/contributing.rst`.
> * in `tox.ini`, there are a few `PARITY_` environment variables that are now obsolete
> 
> There are also a bunch of other references to actually running parity scattered throughout the docs, but I'll open up a new issue for those.

ahhhh good catch ty 🙏

**Comment by mgmanzella** [comment]
hiyo @kclowes ! finally was able to make those revisions, hopefully i didn't miss anything else 🙏

**Review by kclowes — APPROVED** [review]
Awesome, thanks @mgmanzella! Looks good to me!

**Pull request merged**
