### PR TITLE
Fixes event logging bug in utils/events.py

### PR DESCRIPTION
**Pull request by gakonst**
Fixes: https://github.com/ethereum/web3.py/issues/503

### What was wrong?
Events were not getting properly decoded due to use of camelCase instead of snake_case

### How was it fixed?
Changed all occurences of camelCase to snake_case, e.g. logIndex to log_index

#### Cute Animal Picture
le-poodle

### CODE REVIEW

**Comment by gakonst** [comment]
The tests in travis are failing because they are setup to work with TestRPCProvider instead of EthereumTesterProvider, should this go to a different issue?

**Comment by pipermerriam** [comment]
This is fixing the wrong thing.  We need to fix the middleware that the `eth-tester` provider uses to translate to the web3.py version of the data.

In this file: https://github.com/ethereum/web3.py/blob/master/web3/providers/eth_tester/middleware.py

We need to add three new entries to the `results_formatters` for `eth_getLogs`, `eth_getFilterChanges`, and `eth_getFilterLogs` that apply the `log_key_remapper` function.  

Looks like there are some other deficiencies that can be addressed at the same time.  We probably will need a new `log_entry_formatter` to normalize any of the fields in log entries.   Also, that same formatter and remapping needs to be applied to the `logs` field of the receipt which doesn't currently appear to be happening.

**Comment by pipermerriam** [comment]
I just pushed f0f8282 which accounts for the fact that the return from a filter is *sometimes* an event log, but for `pending` and `latest` filters they will be transaction or block hashes.

**Comment by pipermerriam** [comment]
@carver this is good to merge/release  (should also be backported to v3)

**Pull request merged**
