### PR TITLE
Eth tester london updates

### PR DESCRIPTION
**Pull request by fselmo**
### What was wrong?

- Need to update `eth-tester` version to newly released `v0.6.0-beta.2` which includes London support
- Turn on London integration tests and update key mappings for newly introduced params in London (max fees, base fee, effective gas price, etc...)
- Update core tests and integration tests to reflect London changes for eth-tester

### How was it fixed?

- eth-tester version bumped to `v0.6.0-beta.2`
- London core tests updated for eth-tester
- Key mappings updated in `providers/eth-tester/middleware` to match new params for integration tests
- gas price values updated across tests to be >= genesis base fee

### Todo:
- [x] Fill in this template
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

IMG_20211021_085817

### CODE REVIEW

**Comment by unparalleled-js** [comment]
I've checked out your branch and am trying to see if it works for me (as you saw, I had a similar branch where I was able to get it to work for me).

But I am running into this error when calling `web3.eth.max_priority_fee`:

```
RPC Endpoint has not been implemented: eth_maxPriorityFeePerGas
```

**Comment by fselmo** [comment]
> ```
> RPC Endpoint has not been implemented: eth_maxPriorityFeePerGas
> ```

This endpoint has not  been implemented in `eth-tester`. To be certain we're talking about the same thing, you are calling an RPC endpoint here that estimates what the `maxPriorityFeePerGas` should be. Whereas sending a transaction with a `maxPriorityFeePerGas` should work, the estimation endpoint is not implemented in eth-tester.

**Review by kclowes — APPROVED** [review]
LGTM! Thank you for doing all this work! The only thing I was thinking was that it might be nice to do the conversion to Wei in the examples instead of a big number. For example, instead of `1000000000`, do `Web3.toWei(1, 'gwei')`. But feel free to take it or leave it!

**Comment by fselmo** [comment]
> LGTM! Thank you for doing all this work! The only thing I was thinking was that it might be nice to do the conversion to Wei in the examples instead of a big number. For example, instead of `1000000000`, do `Web3.toWei(1, 'gwei')`. But feel free to take it or leave it!

I do like that, it is more clear. Even over 10 ** 9. I will add this. Thanks!

**Comment by unparalleled-js** [comment]
> > ```
> > RPC Endpoint has not been implemented: eth_maxPriorityFeePerGas
> > ```
> 
> This endpoint has not been implemented in `eth-tester`. To be certain we're talking about the same thing, you are calling an RPC endpoint here that estimates what the `maxPriorityFeePerGas` should be. Whereas sending a transaction with a `maxPriorityFeePerGas` should work, the estimation endpoint is not implemented in eth-tester.
> 
> Edit: I think I see what you mean... you had a static return there. I would be good with the static return @unparalleled-js, is this what you meant?

Weird, for whatever reason it works on my branch still! Does this something in this work explicitly make it raise an exception or something?

**Comment by fselmo** [comment]
> > > ```
> > > RPC Endpoint has not been implemented: eth_maxPriorityFeePerGas
> > > ```
> > 
> > 
> > This endpoint has not been implemented in `eth-tester`. To be certain we're talking about the same thing, you are calling an RPC endpoint here that estimates what the `maxPriorityFeePerGas` should be. Whereas sending a transaction with a `maxPriorityFeePerGas` should work, the estimation endpoint is not implemented in eth-tester.
> > Edit: I think I see what you mean... you had a static return there. I would be good with the static return @unparalleled-js, is this what you meant?
> 
> Weird, for whatever reason it works on my branch still! Does this something in this work explicitly make it raise an exception or something?

You actually had implemented a static return for that endpoint which I am perfectly fine with... it will always return 1 gwei but it should be enough to not be broken for testing.

**Pull request merged**
