### PR TITLE
Update package metadata

### PR DESCRIPTION
**Pull request by ofek**
## Background

Hello there! The Python packaging ecosystem has standardized on the interface for build backends ([PEP 517](https://peps.python.org/pep-0517/)/[PEP 660](https://peps.python.org/pep-0660/)) and the format for metadata declaration ([PEP 621](https://peps.python.org/pep-0621/)/[PEP 631](https://peps.python.org/pep-0631/)). As a result, the execution of `setup.py` files is now [deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).

So, I'm spending my free time updating important projects so that they are modernized and set an example for others 😄

## Summary of changes

This implements [PEP 621](https://peps.python.org/pep-0621/), obviating the need for `setup.py` and `MANIFEST.in`. The build backend `hatchling` (of which I am a maintainer in the [PyPA](https://github.com/pypa)) is now used as that is the default in the official [Python packaging tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/). Hatchling is available on all the major distribution channels such as [Debian](https://salsa.debian.org/python-team/packages/hatchling), [Fedora](https://src.fedoraproject.org/rpms/python-hatchling), [Arch Linux](https://archlinux.org/packages/community/any/python-hatchling/), [conda-forge](https://anaconda.org/conda-forge/hatchling), [Nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/hatchling/default.nix), [Alpine Linux](https://github.com/alpinelinux/aports/blob/master/community/py3-hatchling/APKBUILD), [FreeBSD](https://github.com/freebsd/freebsd-ports/blob/main/devel/py-hatchling/Makefile)/[OpenBSD](https://github.com/openbsd/ports/blob/master/devel/py-hatchling/Makefile), [Gentoo Linux](https://github.com/gentoo/gentoo/tree/master/dev-python/hatchling), [MacPorts](https://github.com/macports/macports-ports/blob/master/python/py-hatchling/Portfile), [OpenEmbedded](https://github.com/openembedded/openembedded-core/commit/846e806181f1349be29cbce78c5041735dfd7e6f), [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-hatchling/package.py), etc.

### Version location

The version is now stored in `web3/__init__.py`, removing the need for `pkg_resources` and thus reducing import time of `web3` by ~400ms for me locally.

### Source distribution

The ones on PyPI are erroneously shipping a build artifact `*.egg-info` from `pip install -e .`:

sdist

Also, the old `MANIFEST.in` was trying to ship a `requirements.txt` but there is no such file, only `requirements-docs.txt`.

Both of these issues are now fixed.

## Cute Animal Picture

Nala

### CODE REVIEW

**Comment by kclowes** [comment]
Thanks for this PR! We have a few other things that are higher on our priority list at the moment, so it may take us a bit to review this.

**Comment by ofek** [comment]
@kclowes There was a conflict so I rebased 🙂

**Comment by ofek** [comment]
CI is passing btw

**Comment by ofek** [comment]
@kclowes Your PR https://github.com/ethereum/web3.py/pull/2622 caused many conflicts so I rebased again

**Comment by ofek** [comment]
@kclowes PR https://github.com/ethereum/web3.py/pull/2630 caused another conflict so I rebased again

**Comment by ofek** [comment]
cc @fselmo

**Comment by ofek** [comment]
same errors on master

**Comment by kclowes** [comment]
Thanks @ofek. Once we get The Merge changes out the door across our libraries we'll take a look. Thanks for your patience!

**Comment by ofek** [comment]
@kclowes Good job with The Merge! I rebased to resolve the conflict with your PR https://github.com/ethereum/web3.py/pull/2623

**Comment by ofek** [comment]
@kclowes I rebased to resolve the conflict with your commit to master https://github.com/ethereum/web3.py/commit/1be074567e5126bf8d6f4b3e43dc1465507b173c

**Comment by ofek** [comment]
@kclowes @pacrob I rebased to resolve the conflict with this PR https://github.com/ethereum/web3.py/pull/2657

**Comment by ofek** [comment]
@kclowes @fselmo @pacrob I rebased to resolve the conflict with this commit to master https://github.com/ethereum/web3.py/commit/14cb1216d743bebc08963bbac19760bdcb2df598 and this PR https://github.com/ethereum/web3.py/pull/2671

I don't know how much longer I can keep doing this 😅

**Comment by ofek** [comment]
@kclowes @fselmo @pacrob I rebased to resolve the conflict with this PR https://github.com/ethereum/web3.py/pull/2666

**Comment by pacrob** [comment]
Hi @ofek. I'm sorry we've been so long in getting back to you. We discussed your proposal today and decided that we are going to stick with our current process at this time. For future proposals, please open an issue first so we can discuss changes without putting so much work into it first.

**Comment by ofek** [comment]
Okay! Can you provide any details about why?

**Comment by pacrob** [comment]
Yep. We know our current process and it works well. Hatchling does look good, but there's no compelling reason make the change.

**Comment by ofek** [comment]
What about setuptools + removing setup.py?

**Pull request closed without merging**
