### PR TITLE
Feature/asyncify contract

### PR DESCRIPTION
**Pull request by dbfreem**
removed buildTransaction and estiamteGas since they are being deprecated in the v5 branch.

### CODE REVIEW

**Comment by dbfreem** [comment]
@pacrob I removed buildTransaction and estimateGas since they are being deprecated in v5 #2438.

Also, let me know your thoughts on testing here. That is the last piece left of this async contract.

**Comment by dbfreem** [comment]
just realized doc changes are still needed here I will make those in the next couple days

**Comment by dbfreem** [comment]
made the docs changes

**Comment by pacrob** [comment]
Looks good, thank you! I have a couple more test files to do, should be able to merge them in tomorrow.

**Pull request merged**
