### PR TITLE
Special case for Nethermind\Gnosis revert errors

### PR DESCRIPTION
**Pull request by Aureliaar**
### What was wrong?

Certain forms of errors, eg. generated on Spaceneth\Nethermind setups, would fail to return revert reasons on contracts.
Of the form: 'Reverted 0x4f776e6572496420646f6573206e6f7420657869737420696e207265676973747279'

### How was it fixed?

A small edge case handling was added in the error_formatting.

### Todo:
- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)
This doesn't really seem worth mentioning in release notes. Let me know if that's wanted.

#### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by kclowes** [comment]
Thanks for this!  Do you mind adding a test for this case in [this file](https://github.com/ethereum/web3.py/blob/master/tests/core/utilities/test_method_formatters.py)? I think we should also add a newsfragment, but I'm happy to do that if you don't want to. I can also fix the lint errors too, just let me know.

**Comment by Aureliaar** [comment]
Will do!
Will also try to clean up the linter errors, but feel free to fix up the formatting how you like

**Comment by kclowes** [comment]
sounds good, thanks! eventually we'll have autoformatting on commit, but it hasn't reached the top of our priority queue yet.

**Comment by Aureliaar** [comment]
Having some trouble running the tests locally, hope you don't mind me using your circleci to verify correctness!

**Comment by Aureliaar** [comment]
Tests look fine!

I'd be grateful if you could fix the linter error, it seems to survive a pass of Black Formatter and it's actually pre-existing code

Likewise with the newsfragment. 

Thanks for the prompt responses, and looking forward to seeing this merged

**Comment by kclowes** [comment]
Yep, no problem! Thanks again!

**Pull request merged**
