### PR TITLE
Fix get cached latest block

### PR DESCRIPTION
**Pull request by kamyab98**
### What was wrong?

Fix Issue [#2185](https://github.com/ethereum/web3.py/issues/2185)

### How was it fixed?

- Add validation to params to be list like
- Cast params to tuple and compare

### CODE REVIEW

**Comment by kamyab98** [comment]
> Thank you for this fix! Do you mind adding a test? Otherwise one of us can pick it up soontm :)

Sure, I'll add it.

**Review by Meemaw — APPROVED** [review]
LGTM.

@kclowes can we get this one in? 🙏

**Comment by pacrob** [comment]
Thanks @kamyab98 for fixing and @Meemaw for reporting! 

Closes Issue #2185

**Comment by kclowes** [comment]
@pacrob this should also be backported to v5, do you mind doing that when you get a chance?

**Comment by pacrob** [comment]
Done in #2475

**Pull request merged**
